services:

  roomsbooking:
    container_name: roomsbooking-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./out/logs:/out/logs
      - ./docs:/docs
    depends_on:
      - db-migrations
      - swagger

  db-postgres:
    image: postgres:18.1-bookworm
    container_name: postgres-database
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - ./db/postgres/data:/var/lib/postgresql  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  db-migrations:
    image: migrate/migrate
    container_name: postgres-migrations
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up", "1"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db-postgres:
        condition: service_healthy

  swagger:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.26-alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    container_name: app-swagger
    command: ["init", "-g", "cmd/roomsbooking/main.go", "-o", "docs", "--parseDependency", "--parseInternal"]
    volumes:
      - .:/code
