// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bookings_service_mock

import (
	"backend-assignment-avito/internal/core/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingsRepository creates a new instance of MockBookingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingsRepository {
	mock := &MockBookingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingsRepository is an autogenerated mock type for the BookingsRepository type
type MockBookingsRepository struct {
	mock.Mock
}

type MockBookingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingsRepository) EXPECT() *MockBookingsRepository_Expecter {
	return &MockBookingsRepository_Expecter{mock: &_m.Mock}
}

// CancelBooking provides a mock function for the type MockBookingsRepository
func (_mock *MockBookingsRepository) CancelBooking(ctx context.Context, userId string, bookingId string) (*domain.Booking, error) {
	ret := _mock.Called(ctx, userId, bookingId)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 *domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Booking, error)); ok {
		return returnFunc(ctx, userId, bookingId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Booking); ok {
		r0 = returnFunc(ctx, userId, bookingId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userId, bookingId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingsRepository_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockBookingsRepository_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - bookingId string
func (_e *MockBookingsRepository_Expecter) CancelBooking(ctx interface{}, userId interface{}, bookingId interface{}) *MockBookingsRepository_CancelBooking_Call {
	return &MockBookingsRepository_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, userId, bookingId)}
}

func (_c *MockBookingsRepository_CancelBooking_Call) Run(run func(ctx context.Context, userId string, bookingId string)) *MockBookingsRepository_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingsRepository_CancelBooking_Call) Return(booking *domain.Booking, err error) *MockBookingsRepository_CancelBooking_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingsRepository_CancelBooking_Call) RunAndReturn(run func(ctx context.Context, userId string, bookingId string) (*domain.Booking, error)) *MockBookingsRepository_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsWithPagination provides a mock function for the type MockBookingsRepository
func (_mock *MockBookingsRepository) GetBookingsWithPagination(ctx context.Context, pagination domain.Pagination) ([]domain.Booking, *domain.Pagination, error) {
	ret := _mock.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsWithPagination")
	}

	var r0 []domain.Booking
	var r1 *domain.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Pagination) ([]domain.Booking, *domain.Pagination, error)); ok {
		return returnFunc(ctx, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Pagination) []domain.Booking); ok {
		r0 = returnFunc(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Pagination) *domain.Pagination); ok {
		r1 = returnFunc(ctx, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.Pagination) error); ok {
		r2 = returnFunc(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBookingsRepository_GetBookingsWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsWithPagination'
type MockBookingsRepository_GetBookingsWithPagination_Call struct {
	*mock.Call
}

// GetBookingsWithPagination is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination domain.Pagination
func (_e *MockBookingsRepository_Expecter) GetBookingsWithPagination(ctx interface{}, pagination interface{}) *MockBookingsRepository_GetBookingsWithPagination_Call {
	return &MockBookingsRepository_GetBookingsWithPagination_Call{Call: _e.mock.On("GetBookingsWithPagination", ctx, pagination)}
}

func (_c *MockBookingsRepository_GetBookingsWithPagination_Call) Run(run func(ctx context.Context, pagination domain.Pagination)) *MockBookingsRepository_GetBookingsWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Pagination
		if args[1] != nil {
			arg1 = args[1].(domain.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingsRepository_GetBookingsWithPagination_Call) Return(bookings []domain.Booking, pagination1 *domain.Pagination, err error) *MockBookingsRepository_GetBookingsWithPagination_Call {
	_c.Call.Return(bookings, pagination1, err)
	return _c
}

func (_c *MockBookingsRepository_GetBookingsWithPagination_Call) RunAndReturn(run func(ctx context.Context, pagination domain.Pagination) ([]domain.Booking, *domain.Pagination, error)) *MockBookingsRepository_GetBookingsWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBookings provides a mock function for the type MockBookingsRepository
func (_mock *MockBookingsRepository) GetUserBookings(ctx context.Context, userId string) ([]domain.Booking, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookings")
	}

	var r0 []domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Booking, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Booking); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingsRepository_GetUserBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBookings'
type MockBookingsRepository_GetUserBookings_Call struct {
	*mock.Call
}

// GetUserBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockBookingsRepository_Expecter) GetUserBookings(ctx interface{}, userId interface{}) *MockBookingsRepository_GetUserBookings_Call {
	return &MockBookingsRepository_GetUserBookings_Call{Call: _e.mock.On("GetUserBookings", ctx, userId)}
}

func (_c *MockBookingsRepository_GetUserBookings_Call) Run(run func(ctx context.Context, userId string)) *MockBookingsRepository_GetUserBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingsRepository_GetUserBookings_Call) Return(bookings []domain.Booking, err error) *MockBookingsRepository_GetUserBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingsRepository_GetUserBookings_Call) RunAndReturn(run func(ctx context.Context, userId string) ([]domain.Booking, error)) *MockBookingsRepository_GetUserBookings_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNewBooking provides a mock function for the type MockBookingsRepository
func (_mock *MockBookingsRepository) SaveNewBooking(ctx context.Context, newBooking domain.Booking) (*domain.Booking, error) {
	ret := _mock.Called(ctx, newBooking)

	if len(ret) == 0 {
		panic("no return value specified for SaveNewBooking")
	}

	var r0 *domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Booking) (*domain.Booking, error)); ok {
		return returnFunc(ctx, newBooking)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Booking) *domain.Booking); ok {
		r0 = returnFunc(ctx, newBooking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Booking) error); ok {
		r1 = returnFunc(ctx, newBooking)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingsRepository_SaveNewBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNewBooking'
type MockBookingsRepository_SaveNewBooking_Call struct {
	*mock.Call
}

// SaveNewBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - newBooking domain.Booking
func (_e *MockBookingsRepository_Expecter) SaveNewBooking(ctx interface{}, newBooking interface{}) *MockBookingsRepository_SaveNewBooking_Call {
	return &MockBookingsRepository_SaveNewBooking_Call{Call: _e.mock.On("SaveNewBooking", ctx, newBooking)}
}

func (_c *MockBookingsRepository_SaveNewBooking_Call) Run(run func(ctx context.Context, newBooking domain.Booking)) *MockBookingsRepository_SaveNewBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Booking
		if args[1] != nil {
			arg1 = args[1].(domain.Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingsRepository_SaveNewBooking_Call) Return(booking *domain.Booking, err error) *MockBookingsRepository_SaveNewBooking_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingsRepository_SaveNewBooking_Call) RunAndReturn(run func(ctx context.Context, newBooking domain.Booking) (*domain.Booking, error)) *MockBookingsRepository_SaveNewBooking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotsRepository creates a new instance of MockSlotsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotsRepository {
	mock := &MockSlotsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotsRepository is an autogenerated mock type for the SlotsRepository type
type MockSlotsRepository struct {
	mock.Mock
}

type MockSlotsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotsRepository) EXPECT() *MockSlotsRepository_Expecter {
	return &MockSlotsRepository_Expecter{mock: &_m.Mock}
}

// GetSlot provides a mock function for the type MockSlotsRepository
func (_mock *MockSlotsRepository) GetSlot(ctx context.Context, slotId string) (*domain.Slot, error) {
	ret := _mock.Called(ctx, slotId)

	if len(ret) == 0 {
		panic("no return value specified for GetSlot")
	}

	var r0 *domain.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Slot, error)); ok {
		return returnFunc(ctx, slotId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Slot); ok {
		r0 = returnFunc(ctx, slotId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slotId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotsRepository_GetSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlot'
type MockSlotsRepository_GetSlot_Call struct {
	*mock.Call
}

// GetSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - slotId string
func (_e *MockSlotsRepository_Expecter) GetSlot(ctx interface{}, slotId interface{}) *MockSlotsRepository_GetSlot_Call {
	return &MockSlotsRepository_GetSlot_Call{Call: _e.mock.On("GetSlot", ctx, slotId)}
}

func (_c *MockSlotsRepository_GetSlot_Call) Run(run func(ctx context.Context, slotId string)) *MockSlotsRepository_GetSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlotsRepository_GetSlot_Call) Return(slot *domain.Slot, err error) *MockSlotsRepository_GetSlot_Call {
	_c.Call.Return(slot, err)
	return _c
}

func (_c *MockSlotsRepository_GetSlot_Call) RunAndReturn(run func(ctx context.Context, slotId string) (*domain.Slot, error)) *MockSlotsRepository_GetSlot_Call {
	_c.Call.Return(run)
	return _c
}
