// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package schedules_service_mock

import (
	"backend-assignment-avito/internal/core/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// SaveSchedule provides a mock function for the type MockScheduleRepository
func (_mock *MockScheduleRepository) SaveSchedule(ctx context.Context, schedule domain.Schedule) (*domain.Schedule, error) {
	ret := _mock.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for SaveSchedule")
	}

	var r0 *domain.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Schedule) (*domain.Schedule, error)); ok {
		return returnFunc(ctx, schedule)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Schedule) *domain.Schedule); ok {
		r0 = returnFunc(ctx, schedule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Schedule) error); ok {
		r1 = returnFunc(ctx, schedule)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleRepository_SaveSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSchedule'
type MockScheduleRepository_SaveSchedule_Call struct {
	*mock.Call
}

// SaveSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule domain.Schedule
func (_e *MockScheduleRepository_Expecter) SaveSchedule(ctx interface{}, schedule interface{}) *MockScheduleRepository_SaveSchedule_Call {
	return &MockScheduleRepository_SaveSchedule_Call{Call: _e.mock.On("SaveSchedule", ctx, schedule)}
}

func (_c *MockScheduleRepository_SaveSchedule_Call) Run(run func(ctx context.Context, schedule domain.Schedule)) *MockScheduleRepository_SaveSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Schedule
		if args[1] != nil {
			arg1 = args[1].(domain.Schedule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduleRepository_SaveSchedule_Call) Return(schedule1 *domain.Schedule, err error) *MockScheduleRepository_SaveSchedule_Call {
	_c.Call.Return(schedule1, err)
	return _c
}

func (_c *MockScheduleRepository_SaveSchedule_Call) RunAndReturn(run func(ctx context.Context, schedule domain.Schedule) (*domain.Schedule, error)) *MockScheduleRepository_SaveSchedule_Call {
	_c.Call.Return(run)
	return _c
}
