// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package slots_service_mock

import (
	"backend-assignment-avito/internal/core/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSlotsRepository creates a new instance of MockSlotsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotsRepository {
	mock := &MockSlotsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotsRepository is an autogenerated mock type for the SlotsRepository type
type MockSlotsRepository struct {
	mock.Mock
}

type MockSlotsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotsRepository) EXPECT() *MockSlotsRepository_Expecter {
	return &MockSlotsRepository_Expecter{mock: &_m.Mock}
}

// GetActiveSlots provides a mock function for the type MockSlotsRepository
func (_mock *MockSlotsRepository) GetActiveSlots(ctx context.Context, roomId string, date time.Weekday) ([]domain.Slot, error) {
	ret := _mock.Called(ctx, roomId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSlots")
	}

	var r0 []domain.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Weekday) ([]domain.Slot, error)); ok {
		return returnFunc(ctx, roomId, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Weekday) []domain.Slot); ok {
		r0 = returnFunc(ctx, roomId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Weekday) error); ok {
		r1 = returnFunc(ctx, roomId, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotsRepository_GetActiveSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSlots'
type MockSlotsRepository_GetActiveSlots_Call struct {
	*mock.Call
}

// GetActiveSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId string
//   - date time.Weekday
func (_e *MockSlotsRepository_Expecter) GetActiveSlots(ctx interface{}, roomId interface{}, date interface{}) *MockSlotsRepository_GetActiveSlots_Call {
	return &MockSlotsRepository_GetActiveSlots_Call{Call: _e.mock.On("GetActiveSlots", ctx, roomId, date)}
}

func (_c *MockSlotsRepository_GetActiveSlots_Call) Run(run func(ctx context.Context, roomId string, date time.Weekday)) *MockSlotsRepository_GetActiveSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Weekday
		if args[2] != nil {
			arg2 = args[2].(time.Weekday)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSlotsRepository_GetActiveSlots_Call) Return(slots []domain.Slot, err error) *MockSlotsRepository_GetActiveSlots_Call {
	_c.Call.Return(slots, err)
	return _c
}

func (_c *MockSlotsRepository_GetActiveSlots_Call) RunAndReturn(run func(ctx context.Context, roomId string, date time.Weekday) ([]domain.Slot, error)) *MockSlotsRepository_GetActiveSlots_Call {
	_c.Call.Return(run)
	return _c
}

// IsSlotsBusy provides a mock function for the type MockSlotsRepository
func (_mock *MockSlotsRepository) IsSlotsBusy(ctx context.Context, roomId string, date time.Weekday) (bool, error) {
	ret := _mock.Called(ctx, roomId, date)

	if len(ret) == 0 {
		panic("no return value specified for IsSlotsBusy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Weekday) (bool, error)); ok {
		return returnFunc(ctx, roomId, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Weekday) bool); ok {
		r0 = returnFunc(ctx, roomId, date)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Weekday) error); ok {
		r1 = returnFunc(ctx, roomId, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotsRepository_IsSlotsBusy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSlotsBusy'
type MockSlotsRepository_IsSlotsBusy_Call struct {
	*mock.Call
}

// IsSlotsBusy is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId string
//   - date time.Weekday
func (_e *MockSlotsRepository_Expecter) IsSlotsBusy(ctx interface{}, roomId interface{}, date interface{}) *MockSlotsRepository_IsSlotsBusy_Call {
	return &MockSlotsRepository_IsSlotsBusy_Call{Call: _e.mock.On("IsSlotsBusy", ctx, roomId, date)}
}

func (_c *MockSlotsRepository_IsSlotsBusy_Call) Run(run func(ctx context.Context, roomId string, date time.Weekday)) *MockSlotsRepository_IsSlotsBusy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Weekday
		if args[2] != nil {
			arg2 = args[2].(time.Weekday)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSlotsRepository_IsSlotsBusy_Call) Return(b bool, err error) *MockSlotsRepository_IsSlotsBusy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSlotsRepository_IsSlotsBusy_Call) RunAndReturn(run func(ctx context.Context, roomId string, date time.Weekday) (bool, error)) *MockSlotsRepository_IsSlotsBusy_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSlots provides a mock function for the type MockSlotsRepository
func (_mock *MockSlotsRepository) SaveSlots(ctx context.Context, slots []domain.Slot) ([]domain.Slot, error) {
	ret := _mock.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for SaveSlots")
	}

	var r0 []domain.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Slot) ([]domain.Slot, error)); ok {
		return returnFunc(ctx, slots)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Slot) []domain.Slot); ok {
		r0 = returnFunc(ctx, slots)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.Slot) error); ok {
		r1 = returnFunc(ctx, slots)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotsRepository_SaveSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSlots'
type MockSlotsRepository_SaveSlots_Call struct {
	*mock.Call
}

// SaveSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - slots []domain.Slot
func (_e *MockSlotsRepository_Expecter) SaveSlots(ctx interface{}, slots interface{}) *MockSlotsRepository_SaveSlots_Call {
	return &MockSlotsRepository_SaveSlots_Call{Call: _e.mock.On("SaveSlots", ctx, slots)}
}

func (_c *MockSlotsRepository_SaveSlots_Call) Run(run func(ctx context.Context, slots []domain.Slot)) *MockSlotsRepository_SaveSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Slot
		if args[1] != nil {
			arg1 = args[1].([]domain.Slot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlotsRepository_SaveSlots_Call) Return(slots1 []domain.Slot, err error) *MockSlotsRepository_SaveSlots_Call {
	_c.Call.Return(slots1, err)
	return _c
}

func (_c *MockSlotsRepository_SaveSlots_Call) RunAndReturn(run func(ctx context.Context, slots []domain.Slot) ([]domain.Slot, error)) *MockSlotsRepository_SaveSlots_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// GetScheduleByRoomId provides a mock function for the type MockScheduleRepository
func (_mock *MockScheduleRepository) GetScheduleByRoomId(ctx context.Context, roomID string) (*domain.Schedule, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduleByRoomId")
	}

	var r0 *domain.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Schedule, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Schedule); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleRepository_GetScheduleByRoomId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduleByRoomId'
type MockScheduleRepository_GetScheduleByRoomId_Call struct {
	*mock.Call
}

// GetScheduleByRoomId is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockScheduleRepository_Expecter) GetScheduleByRoomId(ctx interface{}, roomID interface{}) *MockScheduleRepository_GetScheduleByRoomId_Call {
	return &MockScheduleRepository_GetScheduleByRoomId_Call{Call: _e.mock.On("GetScheduleByRoomId", ctx, roomID)}
}

func (_c *MockScheduleRepository_GetScheduleByRoomId_Call) Run(run func(ctx context.Context, roomID string)) *MockScheduleRepository_GetScheduleByRoomId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduleRepository_GetScheduleByRoomId_Call) Return(schedule *domain.Schedule, err error) *MockScheduleRepository_GetScheduleByRoomId_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockScheduleRepository_GetScheduleByRoomId_Call) RunAndReturn(run func(ctx context.Context, roomID string) (*domain.Schedule, error)) *MockScheduleRepository_GetScheduleByRoomId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomsRepository creates a new instance of MockRoomsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomsRepository {
	mock := &MockRoomsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomsRepository is an autogenerated mock type for the RoomsRepository type
type MockRoomsRepository struct {
	mock.Mock
}

type MockRoomsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomsRepository) EXPECT() *MockRoomsRepository_Expecter {
	return &MockRoomsRepository_Expecter{mock: &_m.Mock}
}

// GetRoom provides a mock function for the type MockRoomsRepository
func (_mock *MockRoomsRepository) GetRoom(ctx context.Context, roomId string) (*domain.Room, error) {
	ret := _mock.Called(ctx, roomId)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 *domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Room, error)); ok {
		return returnFunc(ctx, roomId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Room); ok {
		r0 = returnFunc(ctx, roomId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomsRepository_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type MockRoomsRepository_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomId string
func (_e *MockRoomsRepository_Expecter) GetRoom(ctx interface{}, roomId interface{}) *MockRoomsRepository_GetRoom_Call {
	return &MockRoomsRepository_GetRoom_Call{Call: _e.mock.On("GetRoom", ctx, roomId)}
}

func (_c *MockRoomsRepository_GetRoom_Call) Run(run func(ctx context.Context, roomId string)) *MockRoomsRepository_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomsRepository_GetRoom_Call) Return(room *domain.Room, err error) *MockRoomsRepository_GetRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomsRepository_GetRoom_Call) RunAndReturn(run func(ctx context.Context, roomId string) (*domain.Room, error)) *MockRoomsRepository_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}
